(part "RK3506G2"
    (packageRef "QFN35P1230X1230X145-129N-D")
    (interface
        (port "1" (symbPinId 1) (portName "SPI0_MOSI/RM_IO17/GPIO0_C1_D") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SPI0_CLK/RM_IO16/GPIO0_C0_D") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SAI1_SDO3/SPI0_CSN1/RM_IO15/GPIO0_B7_D") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SAI1_SDO2/SPI1_CSN0/RM_IO14/GPIO0_B6_D") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SAI1_SDO1/RM_IO13/GPIO0_B5_D") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SAI1_SDO0/RM_IO12/GPIO0_B4_D") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SAI1_SDI/RM_IO11/GPIO0_B3_D") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SAI1_LRCK/SPI1_MISO/RM_IO10/GPIO0_B2_D") (portType INOUT))
        (port "9" (symbPinId 9) (portName "PMUIO_VCC3V3") (portType INOUT))
        (port "10" (symbPinId 10) (portName "NPOR") (portType INOUT))
        (port "11" (symbPinId 11) (portName "PMU_LOGIC_DVDD0V9") (portType INOUT))
        (port "12" (symbPinId 12) (portName "SAI1_SCLK/SPI1_MOSI/RM_IO9/GPIO0_B1_D") (portType INOUT))
        (port "13" (symbPinId 13) (portName "SAI1_MCLK/SPI1_CLK/RM_IO8/GPIO0_B0_D") (portType INOUT))
        (port "14" (symbPinId 14) (portName "SAI0_SDI3/SPI1_CSN1/RM_IO7/GPIO0_A7_D") (portType INOUT))
        (port "15" (symbPinId 15) (portName "SAI0_SDI2/RM_IO6/GPIO0_A6_D") (portType INOUT))
        (port "16" (symbPinId 16) (portName "SAI0_SDI1/RM_IO5/GPIO0_A5_D") (portType INOUT))
        (port "17" (symbPinId 17) (portName "SAI0_SDI0/RM_IO4/GPIO0_A4_D") (portType INOUT))
        (port "18" (symbPinId 18) (portName "SAI0_SDO/RM_IO3/GPIO0_A3_D") (portType INOUT))
        (port "19" (symbPinId 19) (portName "SAI0_MCLK/RM_IO2/GPIO0_A2_U") (portType INOUT))
        (port "20" (symbPinId 20) (portName "SAI0_SCLK/RM_IO1/GPIO0_A1_D") (portType INOUT))
        (port "21" (symbPinId 21) (portName "SAI0_LRCK/RM_IO0/GPIO0_A0_U") (portType INOUT))
        (port "22" (symbPinId 22) (portName "DDR_VDDQ_1") (portType INOUT))
        (port "23" (symbPinId 23) (portName "DDR_VDDQ_2") (portType INOUT))
        (port "24" (symbPinId 24) (portName "VSS_1") (portType INOUT))
        (port "25" (symbPinId 25) (portName "DDR_VDDQ_3") (portType INOUT))
        (port "26" (symbPinId 26) (portName "SAI2_MCLK_M0/ETH_RMII1_RXDVCRS/GPIO3_B6_D") (portType INOUT))
        (port "27" (symbPinId 27) (portName "UART5_RTSN_M0/ETH_RMII1_MDIO/GPIO3_B5_D") (portType INOUT))
        (port "28" (symbPinId 28) (portName "UART5_TX_M0/ETH_RMII1_MDC/GPIO3_B4_D") (portType INOUT))
        (port "29" (symbPinId 29) (portName "UART5_RX_M0/ETH_RMII1_TXEN/GPIO3_B3_D") (portType INOUT))
        (port "30" (symbPinId 30) (portName "UART5_CTSN_M0/ETH_RMII1_TXD1/GPIO3_B2_D") (portType INOUT))
        (port "31" (symbPinId 31) (portName "SAI2_LRCK_M0/ETH_RMII1_TXD0/GPIO3_B1_D") (portType INOUT))
        (port "32" (symbPinId 32) (portName "SAI2_SDO_M0/ETH_RMII1_CLK/GPIO3_B0_D") (portType INOUT))
        (port "33" (symbPinId 33) (portName "SAI2_SCLK_M0/ETH_RMII1_RXD1/GPIO3_A7_D") (portType INOUT))
        (port "34" (symbPinId 34) (portName "SAI2_SDI_M0/ETH_RMII1_RXD0/GPIO3_A6_D") (portType INOUT))
        (port "35" (symbPinId 35) (portName "SDMMC_D1/TEST_CLK_OUT/GPIO3_A3_D") (portType INOUT))
        (port "36" (symbPinId 36) (portName "SDMMC_D0/GPIO3_A2_D") (portType INOUT))
        (port "37" (symbPinId 37) (portName "SDMMC_CLK/GPIO3_A0_D") (portType INOUT))
        (port "38" (symbPinId 38) (portName "SDMMC_CMD/GPIO3_A1_D") (portType INOUT))
        (port "39" (symbPinId 39) (portName "VCCIO4_VCC") (portType INOUT))
        (port "40" (symbPinId 40) (portName "SDMMC_D3/JTAG_TMS_M0/GPIO3_A5_D") (portType INOUT))
        (port "41" (symbPinId 41) (portName "SDMMC_D2/JTAG_TCK_M0/GPIO3_A4_D") (portType INOUT))
        (port "42" (symbPinId 42) (portName "ETH_RMII0_RXDVCRS/SAI3_MCLK/GPIO2_C0_D") (portType INOUT))
        (port "43" (symbPinId 43) (portName "ETH_RMII0_MDIO/DSM_AUD_LP_M1/SAI3_SDO/GPIO2_B7_D") (portType INOUT))
        (port "44" (symbPinId 44) (portName "ETH_RMII0_MDC/DSM_AUD_LN_M1/SAI3_SDI/GPIO2_B6_D") (portType INOUT))
        (port "45" (symbPinId 45) (portName "ETH_RMII0_TXEN/DSM_AUD_RP_M1/SAI3_LRCK/GPIO2_B5_D") (portType INOUT))
        (port "46" (symbPinId 46) (portName "ETH_RMII0_TXD1/DSM_AUD_RN_M1/SAI3_SCLK/GPIO2_B4_D") (portType INOUT))
        (port "47" (symbPinId 47) (portName "ETH_RMII0_TXD0/SPI2_MISO/GPIO2_B3_D") (portType INOUT))
        (port "48" (symbPinId 48) (portName "ETH_RMII0_CLK/SPI2_MOSI/GPIO2_B2_D") (portType INOUT))
        (port "49" (symbPinId 49) (portName "ETH_RMII0_RXD1/SPI2_CSN/GPIO2_B1_D") (portType INOUT))
        (port "50" (symbPinId 50) (portName "ETH_RMII0_RXD0/SPI2_CLK/GPIO2_B0_D") (portType INOUT))
        (port "51" (symbPinId 51) (portName "LOGIC_DVDD_1") (portType INOUT))
        (port "52" (symbPinId 52) (portName "VCCIO3_VCC") (portType INOUT))
        (port "53" (symbPinId 53) (portName "FSPI_D3/GPIO2_A5_U") (portType INOUT))
        (port "54" (symbPinId 54) (portName "FSPI_CLK/GPIO2_A1_D") (portType INOUT))
        (port "55" (symbPinId 55) (portName "FSPI_D0/GPIO2_A2_U") (portType INOUT))
        (port "56" (symbPinId 56) (portName "VCCIO2_VCC") (portType INOUT))
        (port "57" (symbPinId 57) (portName "FSPI_D2/GPIO2_A4_U") (portType INOUT))
        (port "58" (symbPinId 58) (portName "FSPI_D1/GPIO2_A3_U") (portType INOUT))
        (port "59" (symbPinId 59) (portName "FSPI_CSN/GPIO2_A0_U") (portType INOUT))
        (port "60" (symbPinId 60) (portName "SARADC_IN3/GPIO4_B3_Z") (portType INOUT))
        (port "61" (symbPinId 61) (portName "SARADC_IN2/GPIO4_B2_Z") (portType INOUT))
        (port "62" (symbPinId 62) (portName "SARADC_IN1/GPIO4_B1_Z") (portType INOUT))
        (port "63" (symbPinId 63) (portName "SARADC_IN0/GPIO4_B0_Z") (portType INOUT))
        (port "64" (symbPinId 64) (portName "AVCC_1V8") (portType INOUT))
        (port "65" (symbPinId 65) (portName "ACODEC_ADC_AVDD1V6") (portType INOUT))
        (port "66" (symbPinId 66) (portName "ACODEC_ADC_VCM") (portType INOUT))
        (port "67" (symbPinId 67) (portName "ACODEC_ADC_INN") (portType INOUT))
        (port "68" (symbPinId 68) (portName "ACODEC_ADC_INP") (portType INOUT))
        (port "69" (symbPinId 69) (portName "ACODEC_ADC_AVSS") (portType INOUT))
        (port "70" (symbPinId 70) (portName "USB20_OTG_AVDD3V3") (portType INOUT))
        (port "71" (symbPinId 71) (portName "USB20_OTG0_DM") (portType INOUT))
        (port "72" (symbPinId 72) (portName "USB20_OTG0_DP") (portType INOUT))
        (port "73" (symbPinId 73) (portName "USB20_OTG1_DM") (portType INOUT))
        (port "74" (symbPinId 74) (portName "USB20_OTG1_DP") (portType INOUT))
        (port "75" (symbPinId 75) (portName "AVDD_0V9") (portType INOUT))
        (port "76" (symbPinId 76) (portName "AVDD_1V8") (portType INOUT))
        (port "77" (symbPinId 77) (portName "MIPI_DPHY_DSI_TX_CLKN/GPO4_A4_Z") (portType INOUT))
        (port "78" (symbPinId 78) (portName "MIPI_DPHY_DSI_TX_CLKP/GPO4_A5_Z") (portType INOUT))
        (port "79" (symbPinId 79) (portName "MIPI_DPHY_DSI_TX_D1N/GPO4_A2_Z") (portType INOUT))
        (port "80" (symbPinId 80) (portName "MIPI_DPHY_DSI_TX_D1P/GPO4_A3_Z") (portType INOUT))
        (port "81" (symbPinId 81) (portName "MIPI_DPHY_DSI_TX_D0N/GPO4_A0_Z") (portType INOUT))
        (port "82" (symbPinId 82) (portName "MIPI_DPHY_DSI_TX_D0P/GPO4_A1_Z") (portType INOUT))
        (port "83" (symbPinId 83) (portName "VO_LCDC_DEN/DSMC_CLKP/FLEXBUS1_D0/GPIO1_A0_D") (portType INOUT))
        (port "84" (symbPinId 84) (portName "VO_LCDC_VSYNC/DSMC_CLKN/FLEXBUS1_D1/DSMC_INT0/DSMC_SLV_I_NT/GPIO1_A1_D") (portType INOUT))
        (port "85" (symbPinId 85) (portName "CPU_DVDD_1") (portType INOUT))
        (port "86" (symbPinId 86) (portName "VSS_2") (portType INOUT))
        (port "87" (symbPinId 87) (portName "LOGIC_DVDD_2") (portType INOUT))
        (port "88" (symbPinId 88) (portName "VO_LCDC_HSYNC/DSMC_DQS0/FLEXBUS1_D2/GPIO1_A2_D") (portType INOUT))
        (port "89" (symbPinId 89) (portName "VO_LCDC_CLK/DSMC_D0/FLEXBUS1_D3/GPIO1_A3_D") (portType INOUT))
        (port "90" (symbPinId 90) (portName "VO_LCDC_D23/DSMC_D1/FLEXBUS1_D4/GPIO1_A4_D") (portType INOUT))
        (port "91" (symbPinId 91) (portName "VO_LCDC_D22/DSMC_D2/FLEXBUS1_D5/GPIO1_A5_D") (portType INOUT))
        (port "92" (symbPinId 92) (portName "VCCIO1_VCC_1") (portType INOUT))
        (port "93" (symbPinId 93) (portName "VO_LCDC_D21/DSMC_D3/FLEXBUS1_D6/GPIO1_A6_D") (portType INOUT))
        (port "94" (symbPinId 94) (portName "VO_LCDC_D20/DSMC_D4/FLEXBUS1_D7/GPIO1_A7_D") (portType INOUT))
        (port "95" (symbPinId 95) (portName "VO_LCDC_D19/DSMC_D5/FLEXBUS1_D8/FLEXBUS0_CSN_M0/GPIO1_B0__D") (portType INOUT))
        (port "96" (symbPinId 96) (portName "VO_LCDC_D18/DSMC_CSN1/FLEXBUS1_D9/FLEXBUS1_CSN_M0/UART5__CTSN_M1/RM_IO24/GPIO1_B1_D") (portType INOUT))
        (port "97" (symbPinId 97) (portName "VO_LCDC_D17/DSMC_INT2/FLEXBUS1_D10/FLEXBUS0_D15/FLEXBUS0__CSN_M1/SAI2_SCLK_M1/RM_IO25/GPIO1_B2_D") (portType INOUT))
        (port "98" (symbPinId 98) (portName "VO_LCDC_D16/DSMC_INT3/FLEXBUS1_D11/FLEXBUS0_D14/FLEXBUS1__CSN_M1/SAI2_LRCK_M1/RM_IO26/GPIO1_B3_D") (portType INOUT))
        (port "99" (symbPinId 99) (portName "VO_LCDC_D15/DSMC_D6/FLEXBUS1_D12/FLEXBUS0_D13/FLEXBUS0_C_SN_M2/GPIO1_B4_D") (portType INOUT))
        (port "100" (symbPinId 100) (portName "VO_LCDC_D14/DSMC_D7/FLEXBUS1_D13/FLEXBUS0_D12/FLEXBUS1_C_SN_M2/GPIO1_B5_D") (portType INOUT))
        (port "101" (symbPinId 101) (portName "VO_LCDC_D13/DSMC_CSN0/FLEXBUS1_D14/FLEXBUS0_D11/FLEXBUS0__CSN_M3/GPIO1_B6_D") (portType INOUT))
        (port "102" (symbPinId 102) (portName "VO_LCDC_D12/DSMC_RDYN/FLEXBUS1_D15/FLEXBUS0_D10/FLEXBUS1__CSN_M3/GPIO1_B7_D") (portType INOUT))
        (port "103" (symbPinId 103) (portName "VCCIO1_VCC_2") (portType INOUT))
        (port "104" (symbPinId 104) (portName "VO_LCDC_D11/DSMC_RESETN/FLEXBUS1_CLK/DSMC_INT1/FLEXBUS0__CSN_M4/DSMC_SLV_CLK/GPIO1_C0_D") (portType INOUT))
        (port "105" (symbPinId 105) (portName "VO_LCDC_D10/DSMC_D8/FLEXBUS0_CLK/DSM_AUD_RN_M0/FLEXBUS1__CSN_M4/SAI2_MCLK_M1/DSMC_SLV_DQS0/GPIO1_C1_") (portType INOUT))
        (port "106" (symbPinId 106) (portName "VO_LCDC_D9/DSMC_D9/FLEXBUS0_D9/DSM_AUD_RP_M0/FLEXBUS0_C_SN_M5/SAI2_SDI_M1/RM_IO27/DSMC_SLV_D0/GPIO1_") (portType INOUT))
        (port "107" (symbPinId 107) (portName "VO_LCDC_D8/DSMC_D10/FLEXBUS0_D8/FLEXBUS1_CSN_M5/SAI2_SDO__M1/RM_IO28/DSMC_SLV_D1/GPIO1_C3_D") (portType INOUT))
        (port "108" (symbPinId 108) (portName "VO_LCDC_D7/DSMC_D11/FLEXBUS0_D7/DSMC_SLV_D2/GPIO1_C4_D") (portType INOUT))
        (port "109" (symbPinId 109) (portName "VO_LCDC_D6/DSMC_D12/FLEXBUS0_D6/DSMC_SLV_D3/GPIO1_C5_D") (portType INOUT))
        (port "110" (symbPinId 110) (portName "LOGIC_DVDD_3") (portType INOUT))
        (port "111" (symbPinId 111) (portName "VSS_3") (portType INOUT))
        (port "112" (symbPinId 112) (portName "CPU_DVDD_2") (portType INOUT))
        (port "113" (symbPinId 113) (portName "VO_LCDC_D5/DSMC_D13/FLEXBUS0_D5/DSMC_SLV_D4/GPIO1_C6_D") (portType INOUT))
        (port "114" (symbPinId 114) (portName "VO_LCDC_D4/DSMC_D14/FLEXBUS0_D4/DSMC_SLV_D5/GPIO1_C7_D") (portType INOUT))
        (port "115" (symbPinId 115) (portName "VO_LCDC_D3/DSMC_D15/FLEXBUS0_D3/DSM_AUD_LN_M0/DSMC_SLV__D6/GPIO1_D0_D") (portType INOUT))
        (port "116" (symbPinId 116) (portName "VO_LCDC_D2/DSMC_DQS1/FLEXBUS0_D2/DSM_AUD_LP_M0/UART5_RT_SN_M1/RM_IO29/DSMC_SLV_D7/GPIO1_D1_D") (portType INOUT))
        (port "117" (symbPinId 117) (portName "VO_LCDC_D1/DSMC_CSN2/FLEXBUS0_D1/UART5_TX_M1/RM_IO30/DSM_C_SLV_CSN0/GPIO1_D2_D") (portType INOUT))
        (port "118" (symbPinId 118) (portName "VO_LCDC_D0/DSMC_CSN3/FLEXBUS0_D0/UART5_RX_M1/RM_IO31/DS_MC_SLV_RDYN/GPIO1_D3_D") (portType INOUT))
        (port "119" (symbPinId 119) (portName "OSC_CLK_OUT/REF_CLK0_OUT/GPIO0_D0_D") (portType INOUT))
        (port "120" (symbPinId 120) (portName "SYS_PLL_AVDD1V8") (portType INOUT))
        (port "121" (symbPinId 121) (portName "OSC_XIN") (portType INOUT))
        (port "122" (symbPinId 122) (portName "OSC_XOUT") (portType INOUT))
        (port "123" (symbPinId 123) (portName "UART0_RX/JTAG_TMS_M1/RM_IO23/GPIO0_C7_U") (portType INOUT))
        (port "124" (symbPinId 124) (portName "UART0_TX/JTAG_TCK_M1/RM_IO22/GPIO0_C6_U") (portType INOUT))
        (port "125" (symbPinId 125) (portName "CPU_AVS/RM_IO21/GPIO0_C5_Z") (portType INOUT))
        (port "126" (symbPinId 126) (portName "ETH_CLK0_25M_OUT/AUPLL_CLK_IN/RM_IO20/GPIO0_C4_D") (portType INOUT))
        (port "127" (symbPinId 127) (portName "ETH_CLK1_25M_OUT/SPI0_CSN0/RM_IO19/GPIO0_C3_D") (portType INOUT))
        (port "128" (symbPinId 128) (portName "REF_CLK1_OUT/SPI0_MISO/RM_IO18/GPIO0_C2_D") (portType INOUT))
        (port "129" (symbPinId 129) (portName "VSS_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Rockchip")
    (property "Manufacturer_Part_Number" "RK3506G2")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "QFN-128(12.3x12.3) Microcontrollers RoHS 440 mV,,2.5 V,1200 MHz,98 dB,250 mV,62.5 ohm ,-20 25 80 ")
    (property "Datasheet_Link" "https://opensource.rock-chips.com/images/5/51/Rockchip_RK3506G2_Datasheet_V1.3-20250811.pdf")
    (property "symbolName1" "RK3506G2")
)
